### ISSUE TITLE
numberBox 的一个 bug

### ISSUE THREAD

**Issue by DrRua** [dingyong0214/ThorUI#19]
在小程序使用 numberBox 组件的过程中，发现多次输入小于最小值的时候，第二次开始输入框就不会自动重置成最小值，看了一下代码
`if ((value == this.data.value && value != this.data.inputValue) || !e.detail.value) {
        this.setData({
          inputValue: value
        })
      }`
不知前半部分的判断是为了限制什么，求解答！谢谢！

**Comment by dingyong0214** [comment]
这里延用了uni的写法，改一下判断if (value != e.detail.value || value != this.data.inputValue) {}
