### ISSUE TITLE
无聊的提个意见

### ISSUE THREAD

**Issue by qi19901212** [dingyong0214/ThorUI#2]
兄弟咋不建个群呢？

**Comment by dingyong0214** [comment]
前几天创建了一个，还没怎么放出去：745733024------------------ 原始邮件 ------------------
发件人: "Wukong"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 晚上9:30
收件人: "dingyong0214/ThorUI"<ThorUI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [dingyong0214/ThorUI] 无聊的提个意见 (#2)



兄弟咋不建个群呢？
 
&mdash;

**Comment by qi19901212** [comment]
我觉得你这个做的挺好的，就是可能现在人用的少。在运作运作 应该能有不少人

**Comment by dingyong0214** [comment]
等我完善完善，还有很多功能需要加入


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wukong <notifications@github.com>
发送时间: 2019年7月22日 21:50
收件人: dingyong0214/ThorUI <ThorUI@noreply.github.com>
抄送: echo. <1062884167@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[dingyong0214/ThorUI] 无聊的提个意见 (#2)




我觉得你这个做的挺好的，就是可能现在人用的少。在运作运作 应该能有不少人

**Comment by dingyong0214** [comment]
欢迎加入qq群：745733024
