### ISSUE TITLE
  bottom: env(safe-area-inset-bottom); 不生效

### ISSUE THREAD

**Issue by jzsn2018** [dingyong0214/ThorUI#21]
footer组件中的这段样式,影响组件渲染, 初步排查是  bottom: env(safe-area-inset-bottom); 这个的影响
.tui-fixed {
  position: fixed;
  bottom: env(safe-area-inset-bottom);
  z-index: 9999;
}

**Comment by dingyong0214** [comment]
该组件库已更新至V1.6.0，开源版本目前为V1.4.2，详见文档：https://thorui.cn/doc
