### ISSUE TITLE
小程序构建失败

### ISSUE THREAD

**Issue by ww545** [dingyong0214/ThorUI#24]
使用原生的小程序，然后yarn add Thor-ui 下载的是vue的依赖，然后 npm install thor-ui也是的vue版本的。
我下载到了小程序相关demo，是需要手动一个个找依赖关系然后分解吗？

总结：如何在小程序中安装依赖，并且成功构建NPM

**Comment by Doraemon999** [comment]
![image](https://user-images.githubusercontent.com/10330568/170831136-37b951ed-d4ba-49a0-82d5-ea75c6986f0a.png)
请问为何会出现 state的异常 需要怎么修复？

**Comment by dingyong0214** [comment]
目前小程序尚未发布npm包，需要将组件手动引入进项目中

**Comment by Doraemon999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
