### ISSUE TITLE
组件报错

### ISSUE THREAD

**Issue by hiifong** [dingyong0214/ThorUI#25]
message：Error: wxss 编译错误，错误信息：ErrorFileCount[1] ./components/grid-item/grid-item.wxss(1:196): unexpected token `,`
 [20220118 11:54:30][wx3196******7]
appid: wx319**********
openid: o6zAJszU***********Etiw
ideVersion: 1.05.2108130
osType: win32-x64
time: 2022-01-18 11:54:40

![image](https://user-images.githubusercontent.com/89133723/149868297-f18be8ca-b604-43ab-bcd3-bc8a9bf9eeb3.png)

**Comment by hiifong** [comment]
用的是原生小程序，编译时没有报错，到预览编译的时候才报错

**Comment by dingyong0214** [comment]
该问题由于版本回滚导致，已经修复，重新下载即可
