### ISSUE TITLE
uniapp运行项目出现state未定义

### ISSUE THREAD

**Issue by Doraemon999** [dingyong0214/ThorUI#28]
![image](https://user-images.githubusercontent.com/10330568/170831174-f8f586d9-c09a-415a-a440-b77b297609f3.png)
uniapp运行项目出现state未定义，请问如何处理？

**Comment by dingyong0214** [comment]
暂未出现此类问题，需要描述一下具体出现场景与页面，可将对应页面vuex使用暂时关闭即可
