### ISSUE TITLE
tui-countdown 组件 end 事件 设置后能否取消？

### ISSUE THREAD

**Issue by mcwhy** [dingyong0214/ThorUI#30]
tui-countdown 组件 end 事件 设置后能否取消？
我在一个页面设置了倒计时 end事件，在end触发前已经跳转到别的页面了。
这个end事件 到时间后，在别的页面触发了（弹出了一个对话框提醒）。
能不能添加一个取消功能，离开页面前把这个关掉。

**Comment by dingyong0214** [comment]
暂时未暴露手动停止事件,下个版本优化一下、暂时解决办法：end事件如果不需要可以不监听，如果需要监听，跳转页面可进行组件销毁，或者在end监听回调事件中做标识判断
