### ISSUE TITLE
滑动穿透

### ISSUE THREAD

**Issue by pei-zheng-yi** [dingyong0214/ThorUI#8]
商城模板中，<b>pages/extend-view/productList/productList</b>页面中的<b>左侧抽屉</b>及<b>dropDowmList</b>显示时存在滑动穿透的问题

**Comment by pei-zheng-yi** [comment]
drawer and dropdownList elements add this code 'catch:touchmove="preventTouchMove"',
and in the js file realize the 'prevenTouchMove' function like this : preventTouchMove：function(){};
maybe add this in the components file will be better,thanks!

**Comment by dingyong0214** [comment]
下个版本修复
