### ISSUE TITLE
直接使用组件modal出现显示异常问题

### ISSUE THREAD

**Issue by zhangjiuyang** [dingyong0214/ThorUI#9]
![image](https://user-images.githubusercontent.com/14884839/72198453-87559f00-3468-11ea-9703-ad33c9eb48ce.png)

**Comment by zhangjiuyang** [comment]
正常情况
![image](https://user-images.githubusercontent.com/14884839/72198477-2da1a480-3469-11ea-8d9c-398d17685cc3.png)
使用方式
![image](https://user-images.githubusercontent.com/14884839/72198480-40b47480-3469-11ea-92c9-4aee7e1eb252.png)

**Comment by dingyong0214** [comment]
modal插槽内的样式是自定义的，需要自己去写样式，看一下例子使用
